# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d09885c7244c424113849715ecfadbf2289708f2fd08ee95bc1b4c291074fe8841735ac242e4969b4ab268e6da4b66860b8fb5e3188b20360290c8f4b64708f9

test:
  secret_key_base: b757ec27a41129fe64b697696a75c9e025814b0b6866d4a648b4b3a50da80c5349060eaea437962769028be55efe1e222d4068368aedb3ba4ab59f56def871f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
